name:                gpkex-english
version:             0.1.0.0
github:              "NaomiatLibrary/gpkex-english"
license:             BSD3
author:              "Ray Oshikawa"
copyright:           "2021 Ray Oshikawa"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/NaomiatLibrary/gpkex-english>

dependencies:
- base >= 4.7 && < 5
- genprog == 0.1.0.2
- syb
- MonadRandom
- containers
- directory
- split
- chatter
- filepath
- text
library:
  source-dirs: src

executables:
  prepare-run-gp:
    main:                PrepareRunGP.hs
    other-modules:       []
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is PrepareRunGP
    dependencies:
    - gpkex-english
  run-gp:
    main:                RunGP.hs
    other-modules:       []
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is RunGP
    dependencies:
    - gpkex-english
  extraction:
    main:                Extraction.hs
    other-modules:       []
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Extraction
    dependencies:
    - gpkex-english
  evaluation:
    main:                Evaluation.hs
    other-modules:       []
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -main-is Evaluation
    dependencies:
    - gpkex-english

tests:
  gpkex-english-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gpkex-english
